# Generated by Codex on 2026-05-29

import escuela.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_schoolconfiguration_report_fields'),
        ('pagos', '0002_payment_reported_amount_payment_reported_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='academic_year',
            field=models.CharField(default=escuela.models.active_academic_year_default, max_length=9),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='academic_year',
            field=models.CharField(default=escuela.models.active_academic_year_default, max_length=9),
        ),
    ]
