# Generated by Django 6.0.1 on 2026-05-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='alXrcL2NtYiB5UeeOdPQoeOYHecKT381', editable=False, max_length=32, unique=True),
        ),
    ]

