# Generated by Django 6.0.1 on 2026-05-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='k3fe6Apwb8OAutVgEXQFD5oHtFs0vz1z', editable=False, max_length=32, unique=True),
        ),
    ]

