# Generated by Django 6.0.1 on 2026-05-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0018_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='3g6Erk1qcrlMqcbix40b0DiZJsgGoS9p', editable=False, max_length=32, unique=True),
        ),
    ]

