# Generated by Django 6.0.1 on 2026-05-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ymojr1VIjX39HCndtknhpqZIHs1hdEmq', editable=False, max_length=32, unique=True),
        ),
    ]

