# Generated by Django 6.0.1 on 2026-05-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0021_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Bg6axFQNab2FlkQAveQ6qj8DphZAz6Kd', editable=False, max_length=32, unique=True),
        ),
    ]

