# Generated by Django 6.0.1 on 2026-05-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zJ4f9teryYUk3zO8vZEldaMDTZecZ0tn', editable=False, max_length=32, unique=True),
        ),
    ]

