# Generated by Django 6.0.1 on 2026-05-21 02:23

import autenticacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0023_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default=autenticacion.models.generate_password_reset_token, editable=False, max_length=32, unique=True),
        ),
    ]

