# Generated by Django 6.0.1 on 2026-05-24 00:21

import autenticacion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0025_customuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=autenticacion.models.generate_otp, max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código OTP',
                'verbose_name_plural': 'Códigos OTP',
                'ordering': ['-creado_en'],
            },
        ),
    ]
