# Generated by Django 6.0.1 on 2026-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_remove_subject_class_level_subject_class_level'),
        ('profesor', '0002_teacher_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='materia.subject'),
        ),
    ]
