# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_teacher_department_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
