# Generated by Django 6.0.1 on 2026-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('materia', '0001_initial'),
        ('profesor', '0002_teacher_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=10, unique=True)),
                ('section', models.CharField(max_length=5)),
                ('academic_year', models.DateField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('teachers', models.ManyToManyField(blank=True, to='profesor.teacher')),
            ],
            options={
                'ordering': ['academic_year', 'class_id', 'section'],
                'unique_together': {('class_id', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.teacher')),
            ],
            options={
                'verbose_name': 'Class Teacher Assignment',
                'verbose_name_plural': 'Class Teacher Assignments',
                'ordering': ['class_assigned', 'teacher', 'subject'],
                'unique_together': {('class_assigned', 'teacher', 'subject')},
            },
        ),
    ]
