# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_representativeinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='director_document',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='report_footer',
            field=models.TextField(blank=True),
        ),
    ]
