# Generated by Django 6.0.1 on 2026-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_class_classteacherassignment'),
        ('estudiante', '0001_initial'),
        ('materia', '0002_remove_subject_class_level_subject_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='materia.subject'),
        ),
    ]
