# Generated by Django 6.0.1 on 2026-05-08 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_student_cedula_student_etapa_student_grado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('etapa', models.CharField(max_length=20)),
                ('grado', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=5)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.student')),
            ],
        ),
    ]
