# Generated by Django 6.0.1 on 2026-05-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_remove_parent_father_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='present_class',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='subjects',
        ),
    ]
