# Generated by Django 6.0.1 on 2026-05-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0007_student_parent_student_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
