# Generated by Django 6.0.1 on 2026-05-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0008_alter_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='monto_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
