# Generated by Django 6.0.5 on 2026-05-27 02:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0010_parent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-academic_year', 'student__last_name']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='next_academic_year',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='result_status',
            field=models.CharField(choices=[('activo', 'Activo'), ('promovido', 'Promovido'), ('repite', 'Repite'), ('retirado', 'Retirado'), ('egresado', 'Egresado'), ('cerrado', 'Cerrado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
        migrations.CreateModel(
            name='GradeSectionCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('etapa', models.CharField(max_length=20)),
                ('grado', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=15)),
                ('capacity', models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                'ordering': ['academic_year', 'etapa', 'grado', 'section'],
                'unique_together': {('academic_year', 'etapa', 'grado', 'section')},
            },
        ),
        migrations.CreateModel(
            name='StudentDocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_certificate', models.BooleanField(default=False)),
                ('identity_card_copy', models.BooleanField(default=False)),
                ('representative_id_copy', models.BooleanField(default=False)),
                ('student_photos', models.BooleanField(default=False)),
                ('previous_school_certificate', models.BooleanField(default=False)),
                ('vaccination_card', models.BooleanField(default=False)),
                ('medical_report', models.BooleanField(default=False)),
                ('authorizations', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='estudiante.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40)),
                ('medical_insurance', models.CharField(blank=True, max_length=120)),
                ('special_condition', models.TextField(blank=True)),
                ('important_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='estudiante.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('academic_year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('retardo', 'Retardo'), ('justificado', 'Justificado')], default='presente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='estudiante.student')),
            ],
            options={
                'ordering': ['-date', 'student__last_name'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
