# Generated by Django 6.0.5 on 2026-06-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0012_student_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino'), ('Others', 'Otro')], max_length=10),
        ),
    ]
