# Generated by Django 6.0.5 on 2026-05-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgrade',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicgrade',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
