# Generated by Codex on 2026-05-29

import escuela.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_academicgrade_is_locked_academicgrade_weight'),
        ('escuela', '0005_schoolconfiguration_report_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgrade',
            name='academic_year',
            field=models.CharField(default=escuela.models.active_academic_year_default, max_length=9),
        ),
    ]
