# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='report_type',
            field=models.CharField(choices=[('inscripcion', 'Constancia de Inscripcion'), ('solvencia', 'Solvencia'), ('estudio', 'Constancia de Estudio'), ('comportamiento', 'Certificado de Comportamiento')], default='inscripcion', max_length=30),
        ),
        migrations.AddField(
            model_name='constancia',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=9),
        ),
        migrations.AddField(
            model_name='constancia',
            name='representative_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='constancia',
            name='representative_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='constancia',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='constancia',
            name='solvent_until',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='constancia',
            name='behavior_rating',
            field=models.CharField(blank=True, choices=[('Excelente', 'Excelente'), ('Distinguido', 'Distinguido'), ('Suficiente', 'Suficiente')], max_length=30),
        ),
    ]
