# Generated by Codex on 2026-05-29

import escuela.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_schoolconfiguration_report_fields'),
        ('reportes', '0002_constancia_report_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constancia',
            name='academic_year',
            field=models.CharField(default=escuela.models.active_academic_year_default, max_length=9),
        ),
    ]
