# Generated by Django 6.0.1 on 2026-05-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_present_class_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='etapa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tiene_cedula',
            field=models.BooleanField(default=False),
        ),
    ]
