# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_remove_subject_class_level_subject_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
