# Generated by Django 6.0.1 on 2026-05-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0014_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='GTxIMjmHe68q5LTs6anh6aCHqA0WCSn3', editable=False, max_length=32, unique=True),
        ),
    ]
