# Generated by Django 6.0.1 on 2026-05-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0019_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='kkpb5cbVhov4q7eoBFfStZTlkWT4u4kn', editable=False, max_length=32, unique=True),
        ),
    ]
